name: Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
      - name: Run mdl
        uses: actionshub/markdownlint@main
        with:
          filesToIgnoreRegex: "SUMMARY.md"
